CREATE DATABASE faas;
GRANT ALL PRIVILEGES ON DATABASE faas TO postgres;
CREATE TABLE "reguser"(ID VARCHAR PRIMARY KEY NOT NULL, NAME VARCHAR NOT NULL, PASSWORD VARCHAR NOT NULL);
CREATE TABLE "function"(ID VARCHAR PRIMARY KEY NOT NULL, NAME VARCHAR NOT NULL, CONTENT VARCHAR NOT NULL, USERID VARCHAR NOT NULL references "reguser"(id));
CREATE TABLE "request"(ID VARCHAR PRIMARY KEY NOT NULL, TYPE VARCHAR NOT NULL, PARAMETER VARCHAR, STATUS VARCHAR, RESULT VARCHAR, USERID VARCHAR NOT NULL references "reguser"(id));