CREATE DATABASE faas;
GRANT ALL PRIVILEGES ON DATABASE faas TO postgres;
CREATE TABLE "user"(ID INT PRIMARY KEY NOT NULL, NAME VARCHAR NOT NULL, PASSWORD VARCHAR NOT NULL);
CREATE TABLE "function"(ID INT PRIMARY KEY NOT NULL, NAME VARCHAR NOT NULL, CONTENT VARCHAR NOT NULL, USERID int NOT NULL references "user"(id));
CREATE TABLE "request"(ID INT PRIMARY KEY NOT NULL, TYPE VARCHAR NOT NULL, PARAMETER VARCHAR, STATUS VARCHAR, RESULT VARCHAR, USERID int NOT NULL references "user"(id));