CREATE DATABASE faas;
GRANT ALL PRIVILEGES ON DATABASE faas TO postgres;
-- GRANT ALL PRIVILEGES ON DATABASE faas TO ravichandran;
\c faas
CREATE TABLE public."reguser"(ID VARCHAR PRIMARY KEY NOT NULL, NAME VARCHAR NOT NULL, PASSWORD VARCHAR NOT NULL);
CREATE TABLE public."function"(ID VARCHAR PRIMARY KEY NOT NULL, NAME VARCHAR NOT NULL, CONTENT VARCHAR NOT NULL, USERID VARCHAR NOT NULL references "reguser"(id));
CREATE TABLE public."request"(ID VARCHAR PRIMARY KEY NOT NULL, TYPE VARCHAR NOT NULL, PARAMETER VARCHAR, STATUS VARCHAR, RESULT VARCHAR, USERID VARCHAR);